// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';

const SUPABASE_URL = "https://gfoizhyliodlbxxrtniw.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imdmb2l6aHlsaW9kbGJ4eHJ0bml3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTgyNDg1NDgsImV4cCI6MjA3MzgyNDU0OH0.YfdGcb0qswQkTJZa98eSYReGFSIXXEh0CjyKhZiyRxg";

// Import the supabase client like this:
// import { supabase } from "../integrations/supabase/client.js";

export const supabase = createClient(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});
